<a href="https://colab.research.google.com/github/2023002786/2023002786_/blob/main/vector_oper_lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

print("="*60)
print("VECTOR OPERATIONS")
print("="*60)

v1 = np.array([1, 2, 3, 4, 5])
v2 = np.array([5, 4, 3, 2, 1])

print(f"\nVector 1: {v1}")
print(f"Vector 2: {v2}")

print("\nElement-Wise Operations")
print("-"*40)
print(f"Addition: {v1} + {v2} = {v1 + v2}")
print(f"Subtraction: {v1} - {v2} = {v1 - v2}")
print(f"Multiplication: {v1} * {v2} = {v1 * v2}")
print(f"Division: {v1} / {v2} = {v1 / v2}")
print(f"Power: {v1} ** 2 = {v1 ** 2}")

print("\nVector Magnitude")
print("-"*40)
mag_v1 = np.linalg.norm(v1)
mag_v2 = np.linalg.norm(v2)
print(f"Magnitude v1: {mag_v1:.2f}")
print(f"Magnitude v2: {mag_v2:.2f}")

print("\nDot Product")
print("-"*40)
dot_product = np.dot(v1, v2)
print(f"v1 • v2 = {dot_product}")

print("\nCross Product")
print("-"*40)
v3 = np.array([1, 2, 3])
v4 = np.array([4, 5, 6])
cross_product = np.cross(v3, v4)
print(f"v3 = {v3}, v4 = {v4}")
print(f"v3 × v4 = {cross_product}")

print("\nAngle Between Vectors")
print("-"*40)
cos_theta = np.dot(v1, v2) / (mag_v1 * mag_v2)
angle_deg = np.arccos(np.clip(cos_theta, -1, 1)) * 180 / np.pi
print(f"Cos  = {cos_theta:.3f}")
print(f"Angle = {angle_deg:.1f}°")

print("\nNormalized Vectors")
print("-"*40)
v1_norm = v1 / mag_v1
v2_norm = v2 / mag_v2
print(f"Normalized v1: {v1_norm}")
print(f"Normalized v2: {v2_norm}")

print("="*60)

VECTOR OPERATIONS

Vector 1: [1 2 3 4 5]
Vector 2: [5 4 3 2 1]

Element-Wise Operations
----------------------------------------
Addition: [1 2 3 4 5] + [5 4 3 2 1] = [6 6 6 6 6]
Subtraction: [1 2 3 4 5] - [5 4 3 2 1] = [-4 -2  0  2  4]
Multiplication: [1 2 3 4 5] * [5 4 3 2 1] = [5 8 9 8 5]
Division: [1 2 3 4 5] / [5 4 3 2 1] = [0.2 0.5 1.  2.  5. ]
Power: [1 2 3 4 5] ** 2 = [ 1  4  9 16 25]

Vector Magnitude
----------------------------------------
Magnitude v1: 7.42
Magnitude v2: 7.42

Dot Product
----------------------------------------
v1 • v2 = 35

Cross Product
----------------------------------------
v3 = [1 2 3], v4 = [4 5 6]
v3 × v4 = [-3  6 -3]

Angle Between Vectors
----------------------------------------
Cos  = 0.636
Angle = 50.5°

Normalized Vectors
----------------------------------------
Normalized v1: [0.13483997 0.26967994 0.40451992 0.53935989 0.67419986]
Normalized v2: [0.67419986 0.53935989 0.40451992 0.26967994 0.13483997]


In [ ]:
import numpy as np

print("MATRIX Operations")
print("="*70)

# Create matrices
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
C = np.array([[1, 0], [0, 1]])  # Identity 2x2

print(f"\nMatrix A (3x3):\n{A}")
print(f"Matrix B (3x3):\n{B}")
print(f"Matrix C (2x2):\n{C}")

print("\nBasic Operations")
print("-"*50)
print(f"Addition: \n{A + B}")
print(f"Subtraction: \n{A - B}")
print(f"Element-wise: \n{A * B}")
print(f"Scalar multiplication: \n{2 * A}")

print("\nMatrix Multiplication")
print("-"*50)
print(f"A @ B (3x3):\n{np.matmul(A, B)}")
print(f"A @ A^T: \n{np.matmul(A, A.T)}")

print("\nTranspose")
print("-"*50)
print(f"A shape: {A.shape}")
print(f"A transpose shape: {A.T.shape}")
print(f"A^T:\n{A.T}")

print("\nDeterminant & Inverse")
print("-"*50)
det_C = np.linalg.det(C)
inv_C = np.linalg.inv(C)
print(f"Det(C): {det_C:.3f}")
print(f"Inv(C):\n{inv_C}")

print("\nMatrix Properties")
print("-"*50)
print(f"Rank(A): {np.linalg.matrix_rank(A)}")
print(f"Trace(A): {np.trace(A)}")
print(f"Norm(A): {np.linalg.norm(A):.2f}")

print("\nEigenvalues & Eigenvectors")
print("-"*50)
eigvals, eigvecs = np.linalg.eig(A)
print(f"Eigenvalues: {eigvals}")
print(f"Eigenvectors (first column):\n{eigvecs[:, 0]}")

print("\nSolve Linear System: Ax = b")
print("-"*50)
A = np.array([[2, 1, 0], [1, 3, 1], [0, 1, 4]])
b = np.array([1, 2, 3])
x = np.linalg.solve(A, b)
print(f"Solution x: {x}")

print("="*70)

MATRIX Operations

Matrix A (3x3):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B (3x3):
[[9 8 7]
 [6 5 4]
 [3 2 1]]
Matrix C (2x2):
[[1 0]
 [0 1]]

Basic Operations
--------------------------------------------------
Addition: 
[[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction: 
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Element-wise: 
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Scalar multiplication: 
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Matrix Multiplication
--------------------------------------------------
A @ B (3x3):
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
A @ A^T: 
[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]

Transpose
--------------------------------------------------
A shape: (3, 3)
A transpose shape: (3, 3)
A^T:
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Determinant & Inverse
--------------------------------------------------
Det(C): 1.000
Inv(C):
[[1. 0.]
 [0. 1.]]

Matrix Properties
--------------------------------------------------
Rank(A): 2
Trace(A): 15
Norm(A): 16.88

Eigenvalues & Eigenvectors
---